export interface FundingOpportunity {
  id: string
  title: string
  source: string
  url: string
  country: string
  state: string
  city: string
  areas: string[]
  opportunityType: string
  fundingMin: number
  fundingMax: number
  currency: string
  deadline: string | null
  applicantTypes: string[]
  startupStages: string[]
  maturityLevels: string[]
  requiresCnpj: boolean
  requiresMvp: boolean
  requiresRevenue: boolean
  summary: string
  eligibility: string[]
  requiredDocuments: string[]
  evaluationCriteria: string[]
  processSteps: string[]
  status: string
  matchScore: number
  recommendation: string
  risks: string[]
}

export const mockFundingOpportunities: FundingOpportunity[] = [
  {
    id: "demo-nascer-sc",
    title: "Programa Nascer Demo - Pré-incubação de Ideias",
    source: "Ecossistema estadual simulado",
    url: "#demo-nascer-sc",
    country: "Brasil",
    state: "SC",
    city: "Florianópolis",
    areas: ["Tecnologia", "Educação", "IA"],
    opportunityType: "Pré-incubação",
    fundingMin: 0,
    fundingMax: 25000,
    currency: "BRL",
    deadline: "2026-07-15",
    applicantTypes: ["Pessoa física", "Equipe informal"],
    startupStages: ["Ideia inicial", "Validação do problema", "Protótipo"],
    maturityLevels: ["Ideia inicial", "Validação inicial"],
    requiresCnpj: false,
    requiresMvp: false,
    requiresRevenue: false,
    summary: "Oportunidade simulada para equipes em fase inicial estruturarem problema, mercado e protótipo.",
    eligibility: ["Equipe com ao menos duas pessoas", "Problema claro", "Disponibilidade para mentorias"],
    requiredDocuments: ["Resumo da ideia", "Perfil da equipe", "Declaração de disponibilidade"],
    evaluationCriteria: ["Clareza do problema", "Potencial de inovação", "Comprometimento da equipe"],
    processSteps: ["Inscrição", "Pitch curto", "Banca de seleção", "Ciclo de mentorias"],
    status: "Demo",
    matchScore: 82,
    recommendation: "Boa para projetos ainda refinando problema e proposta de valor.",
    risks: ["Pode não aceitar projetos já muito avançados", "Exige presença em mentorias"],
  },
  {
    id: "demo-finep-ai",
    title: "Subvenção Econômica Demo para IA aplicada",
    source: "Agência nacional de inovação simulada",
    url: "#demo-finep-ai",
    country: "Brasil",
    state: "Nacional",
    city: "Online",
    areas: ["IA", "Tecnologia", "Govtech"],
    opportunityType: "Subvenção econômica",
    fundingMin: 100000,
    fundingMax: 500000,
    currency: "BRL",
    deadline: "2026-08-30",
    applicantTypes: ["Empresa"],
    startupStages: ["MVP", "MVP com usuários", "Clientes/pilotos"],
    maturityLevels: ["MVP em desenvolvimento", "MVP validado"],
    requiresCnpj: true,
    requiresMvp: true,
    requiresRevenue: false,
    summary: "Chamada simulada para desenvolvimento tecnológico com IA, validação técnica e impacto econômico.",
    eligibility: ["CNPJ ativo", "Equipe técnica", "Plano de P&D", "MVP ou protótipo funcional"],
    requiredDocuments: ["Contrato social", "Plano de trabalho", "Orçamento", "Currículos da equipe"],
    evaluationCriteria: ["Inovação", "Viabilidade técnica", "Impacto econômico", "Capacidade de execução"],
    processSteps: ["Cadastro", "Projeto técnico", "Análise documental", "Banca técnica"],
    status: "Demo",
    matchScore: 76,
    recommendation: "Relevante para projetos com MVP e capacidade de documentar P&D.",
    risks: ["Exige CNPJ", "Documentação técnica robusta", "Prestação de contas complexa"],
  },
  {
    id: "demo-fap-sp-health",
    title: "Chamada FAP Demo - Healthtech e IA",
    source: "Fundação estadual simulada",
    url: "#demo-fap-sp-health",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    areas: ["Saúde", "Healthtech", "IA"],
    opportunityType: "Grant",
    fundingMin: 50000,
    fundingMax: 250000,
    currency: "BRL",
    deadline: "2026-07-30",
    applicantTypes: ["Empresa", "ICT", "Universidade"],
    startupStages: ["Protótipo", "MVP", "MVP com usuários"],
    maturityLevels: ["Validação inicial", "MVP em desenvolvimento"],
    requiresCnpj: true,
    requiresMvp: false,
    requiresRevenue: false,
    summary: "Edital simulado para validação de soluções digitais em saúde com parceiro científico.",
    eligibility: ["Parceria com instituição técnica", "Plano de validação", "Ética e proteção de dados quando aplicável"],
    requiredDocuments: ["Projeto", "Carta de parceria", "Orçamento", "Plano de dados"],
    evaluationCriteria: ["Impacto em saúde", "Método de validação", "Equipe", "Viabilidade regulatória"],
    processSteps: ["Submissão", "Enquadramento", "Mérito técnico", "Contratação"],
    status: "Demo",
    matchScore: 58,
    recommendation: "Boa se o projeto tiver aderência com saúde ou dados sensíveis.",
    risks: ["Pode exigir parceiro científico", "LGPD e ética podem ser obrigatórios"],
  },
  {
    id: "demo-sebrae-startups",
    title: "Programa SEBRAE Startups Demo",
    source: "Programa de apoio simulado",
    url: "#demo-sebrae-startups",
    country: "Brasil",
    state: "Nacional",
    city: "Online",
    areas: ["Tecnologia", "Educação", "Edtech", "Sustentabilidade"],
    opportunityType: "Aceleração",
    fundingMin: 0,
    fundingMax: 80000,
    currency: "BRL",
    deadline: null,
    applicantTypes: ["MEI", "Empresa", "Equipe informal"],
    startupStages: ["MVP", "MVP com usuários", "Clientes/pilotos"],
    maturityLevels: ["MVP em desenvolvimento", "MVP validado"],
    requiresCnpj: false,
    requiresMvp: true,
    requiresRevenue: false,
    summary: "Programa simulado para mentorias, conexão com mercado e apoio a validação comercial.",
    eligibility: ["MVP demonstrável", "Equipe disponível", "Problema e público definidos"],
    requiredDocuments: ["Pitch deck", "Resumo do MVP", "Dados de tração"],
    evaluationCriteria: ["Potencial de mercado", "Maturidade do MVP", "Equipe", "Aderência ao programa"],
    processSteps: ["Inscrição", "Entrevista", "Diagnóstico", "Aceleração"],
    status: "Demo",
    matchScore: 88,
    recommendation: "Forte para projetos com MVP e primeiros usuários.",
    risks: ["Benefício pode ser não financeiro", "Exige dedicação do time"],
  },
  {
    id: "demo-open-innovation-rj",
    title: "Desafio de Inovação Aberta Demo - Govtech RJ",
    source: "Desafio corporativo/público simulado",
    url: "#demo-open-innovation-rj",
    country: "Brasil",
    state: "RJ",
    city: "Rio de Janeiro",
    areas: ["Govtech", "Tecnologia", "IA"],
    opportunityType: "Inovação aberta",
    fundingMin: 20000,
    fundingMax: 120000,
    currency: "BRL",
    deadline: "2026-06-28",
    applicantTypes: ["Empresa", "Startup"],
    startupStages: ["MVP com usuários", "Clientes/pilotos", "Receita inicial"],
    maturityLevels: ["MVP validado", "Pronto para captação inicial"],
    requiresCnpj: true,
    requiresMvp: true,
    requiresRevenue: false,
    summary: "Desafio simulado para testar soluções digitais em processos públicos e atendimento ao cidadão.",
    eligibility: ["CNPJ", "MVP funcional", "Capacidade de piloto", "Adequação LGPD"],
    requiredDocuments: ["Pitch", "Demonstração", "Plano de piloto", "Documentos fiscais"],
    evaluationCriteria: ["Impacto público", "Viabilidade de piloto", "Escalabilidade", "Segurança"],
    processSteps: ["Inscrição", "Demo day", "Piloto", "Avaliação final"],
    status: "Demo",
    matchScore: 64,
    recommendation: "Útil se houver caso de uso em governo ou serviços públicos.",
    risks: ["Prazo curto", "Exige CNPJ e adequação documental"],
  },
  {
    id: "demo-climate-mg",
    title: "Programa Greentech Demo - Clima e Sustentabilidade",
    source: "Aceleradora climática simulada",
    url: "#demo-climate-mg",
    country: "Brasil",
    state: "MG",
    city: "Belo Horizonte",
    areas: ["Sustentabilidade", "Greentech", "Tecnologia"],
    opportunityType: "Aceleração",
    fundingMin: 30000,
    fundingMax: 150000,
    currency: "BRL",
    deadline: "2026-09-10",
    applicantTypes: ["Startup", "Empresa"],
    startupStages: ["Protótipo", "MVP", "MVP com usuários"],
    maturityLevels: ["MVP em desenvolvimento", "MVP validado"],
    requiresCnpj: false,
    requiresMvp: true,
    requiresRevenue: false,
    summary: "Programa simulado para soluções com impacto ambiental, eficiência ou economia circular.",
    eligibility: ["Impacto ambiental claro", "MVP ou protótipo", "Indicadores de impacto"],
    requiredDocuments: ["Pitch deck", "Métricas de impacto", "Plano de validação"],
    evaluationCriteria: ["Impacto climático", "Modelo de negócio", "Equipe", "Viabilidade"],
    processSteps: ["Inscrição", "Triagem", "Bootcamp", "Banca"],
    status: "Demo",
    matchScore: 42,
    recommendation: "Relevante apenas se o projeto tiver tese ambiental clara.",
    risks: ["Baixa aderência para soluções sem impacto climático"],
  },
  {
    id: "demo-bndes-credit",
    title: "Linha de Crédito Demo para Inovação Digital",
    source: "Banco de desenvolvimento simulado",
    url: "#demo-bndes-credit",
    country: "Brasil",
    state: "Nacional",
    city: "Online",
    areas: ["Tecnologia", "IA", "Educação"],
    opportunityType: "Crédito",
    fundingMin: 100000,
    fundingMax: 1000000,
    currency: "BRL",
    deadline: null,
    applicantTypes: ["Empresa"],
    startupStages: ["Receita inicial", "Pronto para aceleração", "Pronto para captação"],
    maturityLevels: ["Pronto para captação inicial", "Pronto para rodada estruturada"],
    requiresCnpj: true,
    requiresMvp: true,
    requiresRevenue: true,
    summary: "Linha simulada para empresas com receita e plano de investimento em inovação digital.",
    eligibility: ["CNPJ", "Receita comprovada", "Regularidade fiscal", "Capacidade de pagamento"],
    requiredDocuments: ["DRE", "Balanço", "Certidões", "Plano de investimento"],
    evaluationCriteria: ["Capacidade financeira", "Garantias", "Plano de inovação", "Histórico da empresa"],
    processSteps: ["Pré-análise", "Documentos financeiros", "Análise de crédito", "Contratação"],
    status: "Demo",
    matchScore: 35,
    recommendation: "Mais adequado para empresas com receita recorrente e contabilidade organizada.",
    risks: ["Endividamento", "Exige regularidade fiscal", "Pode requerer garantias"],
  },
  {
    id: "demo-university-incubator-pa",
    title: "Chamada Incubadora Universitária Demo",
    source: "Universidade/incubadora simulada",
    url: "#demo-university-incubator-pa",
    country: "Brasil",
    state: "PA",
    city: "Belém",
    areas: ["Educação", "Tecnologia", "Sustentabilidade"],
    opportunityType: "Incubação",
    fundingMin: 0,
    fundingMax: 60000,
    currency: "BRL",
    deadline: "2026-10-05",
    applicantTypes: ["Pessoa física", "Empresa", "Equipe universitária"],
    startupStages: ["Ideia inicial", "Protótipo", "MVP"],
    maturityLevels: ["Validação inicial", "MVP em desenvolvimento"],
    requiresCnpj: false,
    requiresMvp: false,
    requiresRevenue: false,
    summary: "Chamada simulada para incubação com mentorias, laboratório, networking e apoio institucional.",
    eligibility: ["Vínculo regional ou acadêmico desejável", "Proposta inovadora", "Equipe comprometida"],
    requiredDocuments: ["Plano simplificado", "Currículo da equipe", "Pitch de 5 slides"],
    evaluationCriteria: ["Inovação", "Impacto regional", "Equipe", "Viabilidade técnica"],
    processSteps: ["Inscrição", "Pitch", "Entrevista", "Incubação"],
    status: "Demo",
    matchScore: 70,
    recommendation: "Boa para projetos em fase inicial que precisam de apoio institucional.",
    risks: ["Pode exigir vínculo regional", "Benefício financeiro indireto"],
  },
  {
    id: "demo-ai-education-prize",
    title: "Prêmio Demo IA para Educação",
    source: "Instituto privado simulado",
    url: "#demo-ai-education-prize",
    country: "Brasil",
    state: "SP",
    city: "Campinas",
    areas: ["IA", "Educação", "Edtech"],
    opportunityType: "Prêmio",
    fundingMin: 10000,
    fundingMax: 75000,
    currency: "BRL",
    deadline: "2026-07-05",
    applicantTypes: ["Startup", "Equipe informal", "Pesquisadores"],
    startupStages: ["Protótipo", "MVP", "MVP com usuários"],
    maturityLevels: ["MVP em desenvolvimento", "MVP validado"],
    requiresCnpj: false,
    requiresMvp: true,
    requiresRevenue: false,
    summary: "Premiação simulada para soluções com IA aplicadas à educação, tutoria ou gestão de aprendizagem.",
    eligibility: ["Demonstração funcional", "Impacto educacional", "Uso responsável de IA"],
    requiredDocuments: ["Vídeo demo", "Pitch", "Descrição da solução", "Termo de responsabilidade"],
    evaluationCriteria: ["Impacto", "Ética em IA", "Usabilidade", "Potencial de escala"],
    processSteps: ["Inscrição", "Avaliação técnica", "Votação/banca", "Premiação"],
    status: "Demo",
    matchScore: 62,
    recommendation: "Boa se o projeto tiver componente educacional ou IA aplicada.",
    risks: ["Prêmio pode não financiar desenvolvimento contínuo", "Exige demo clara"],
  },
]
